# Generated by Django 4.1.2 on 2022-11-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artiste',
            old_name='firstname',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='artiste',
            old_name='lastname',
            new_name='song',
        ),
    ]
